### ISSUE TITLE
Not able to use reduce with seemingly correct installation

### ISSUE THREAD

**Issue by QingweiMeng1234** [rlabduke/reduce#39]
Hi,

I have pulled the latest version. Reduce seems properly installed on my server, but I am not able to use it. I attached pictures that might illustrate the problem.
![128427697-f40c9c06-1d49-4c0a-bf80-78a0e95dfe1b](https://user-images.githubusercontent.com/19242683/128498437-22407621-3e0e-4d5c-a0d2-e15a2b92ac53.png)
![128427738-92958e4a-6258-4e0a-946e-21c654cfd1af](https://user-images.githubusercontent.com/19242683/128498469-ada794c7-3a6c-471b-86e7-6024734a3857.png)

Best,
Weber

**Comment by russell-taylor** [comment]
The CMakeLists.txt files have only been set up to build the program, not to install it.  When you build, it places the 'reduce' executable in the reduce_src subdirectory under the build directory.  You will need to copy the executable into a directory that is on your path (probably /usr/local/bin) and also install the reduce_wwPDB_het_dict.txt in /usr/local or else use the -DB command-line argument to tell reduce where to find it.

On systems where the Makefile build works, you can use 'make install' in the source directory to build and copy the files.

**Comment by russell-taylor** [comment]
I've added an install target to CMakeLists.txt, so that after a pull, you should be able to install using the following commands in your build directory:
```
cmake .
make
sudo make install
```

**Comment by QingweiMeng1234** [comment]
Successfully Installed! Thanks!
