### ISSUE TITLE
WARNING: atom from a het group will be treated as hydrogen/carbon

### ISSUE THREAD

**Issue by rwxayheee** [rlabduke/reduce#42]
Dear reduce experts, 

My apologies for the multiple posts about using reduce.. I'm using reduce to process a protein-ligand complex which contains a ligand called "P01" and a non-standard residue called "EPI". I have added these two custom het groups to my het_dict.txt. [my_het_dict.txt](https://github.com/rlabduke/reduce/files/6993988/my_het_dict.txt)

In the standard error output I got warning messages like this: 

> Processing file: "P01_structure.pdb.for_reduce"
> WARNING: atom   C4 from P01 will be treated as carbon
> WARNING: atom   C5 from P01 will be treated as carbon
> WARNING: atom   C6 from P01 will be treated as carbon
> WARNING: atom   C7 from P01 will be treated as carbon
> WARNING: atom   C8 from P01 will be treated as carbon
> WARNING: atom   N9 from P01 will be treated as carbon
> WARNING: atom   C3 from P01 will be treated as carbon
> WARNING: atom   N2 from P01 will be treated as carbon
> WARNING: atom   O1 from P01 will be treated as carbon
> Building or keeping OH & SH Hydrogens.
> WARNING: atom HT11 from EPI will be treated as hydrogen
> WARNING: atom HT11 from EPI will be treated as hydrogen
> WARNING: atom HT12 from EPI will be treated as hydrogen
> WARNING: atom HT13 from EPI will be treated as hydrogen
> WARNING: atom HT12 from EPI will be treated as hydrogen
> WARNING: atom HT11 from EPI will be treated as hydrogen
> WARNING: atom HT12 from EPI will be treated as hydrogen
> WARNING: atom HT13 from EPI will be treated as hydrogen
> WARNING: atom HT13 from EPI will be treated as hydrogen
> WARNING: atom HT11 from EPI will be treated as hydrogen
> WARNING: atom HT12 from EPI will be treated as hydrogen
> WARNING: atom HT13 from EPI will be treated as hydrogen
> WARNING: atom HT21 from EPI will be treated as hydrogen
> WARNING: atom HT21 from EPI will be treated as hydrogen
> WARNING: atom HT22 from EPI will be treated as hydrogen
> WARNING: atom HT23 from EPI will be treated as hydrogen
> WARNING: atom HT22 from EPI will be treated as hydrogen
> WARNING: atom HT21 from EPI will be treated as hydrogen

The output pdb structure looks fine to me, and the hydrogen are added to reasonable positions. But I still wonder is such warning normal for custom het groups? Or is it because of the atom names? 

Thank you for your time and kind advice in advance! 

Many Thanks,
Amy

**Comment by russell-taylor** [comment]
Amy,

Glad to help.  It looks like the atom names in P01 are one too many columns to the right.  You can see this by comparing the columns with the EPI entry right above.  This means that Reduce sees the name starting with blank, which it does not recognize.  Anything it does not recognize it calls a Carbon.

Thanks,
Russ

**Comment by rwxayheee** [comment]
Hi Russ, 

Thank you for your kind reply! Yes that was very helpful. I thought the atom names were right justified in het_dict.txt, but I looked at a few more examples and realized that wasn't true.. I modified the atom names in my input file and in het_dict.txt, and now I don't see such warning for the ligand atoms. 

Thank you again for your help! 

Best,
Amy
