### ISSUE TITLE
Residue names for custom het groups

### ISSUE THREAD

**Issue by rwxayheee** [rlabduke/reduce#43]
Dear reduce experts, 

I have a real quick question about the residue names for custom het groups: Are there are any "reserved" residue names that can not be used for new residues/ligands? In my het_dict.txt, I tried two names for exactly the same ligand compound: "P01" worked, but "PCA" didn't work. Here's my het_dict.txt: 
[my_het_dict.txt](https://github.com/rlabduke/reduce/files/7008955/my_het_dict.txt)

With "PCA", the program would skip and not add hydrogens to the ligand, while I didn't see any error messages for unable to recognize the ligand. I was thinking "PCA" might be a reserved name for a more common residue, and I wonder if there are any more "reserved" names like this. I will be more careful and try to avoid using such names for custom het groups. 

Thank you for your time and kind advice in advance! 

Many Thanks,
Amy

**Comment by russell-taylor** [comment]
Amy,

Here is a response from Jane Richardson:

There are several levels of answer.
- Any currently existing entry in the het dict is "reserved".
- You could ask at the PDB which codes are still unused.  They have nearly run out of 3-letter codes, and will soon go to a system with more characters.
- The new version of Reduce to come will get its info from cctbx, not a het dict file (but isn't ready yet).
- When using current Reduce, you could pick whatever 3-letter code seems nice for your new ligand, delete it from the het dict, and replace it with the definition and specs of your new ligand, and I'm pretty sure that would work.
