### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by reneeotten** [rlabduke/reduce#45]
thanks for making this software available! I am in the process of adding the package to [MacPorts](https://www.macports.org) and would like to clarify the license as it's not completely clear to me which is the intended license. Can you tell me which of the [SPDX licenses](https://spdx.org/licenses/) (or something else) you intend to use? Thanks!

**Comment by russell-taylor** [comment]
The license was written in the days before they had been standardized, and it is a bit of a Frankenstein's mash-up.  The different subdirectories have slightly different origins and thus different licenses.  There is a LICENSE.txt in some of the subdirectories that overrides the one in the root directory.

**Comment by reneeotten** [comment]
thanks for the response @russell-taylor ! I already looked at the different LICENSE.txt files in the main project and some of the sub-directories, but couldn't really figure out if it was a "standard" license. 

However, from the text:
`Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms`

would you agree that if I include the LICENSE.txt file and set the license to `Permissive` (which is in MacPorts defined as: "# 'Permissive' is a catchall for other licenses that allow modification and distribution of source and binaries.") this would be an accurate description of the situation?

**Comment by russell-taylor** [comment]
I'll check with the PIs and let you know.

**Comment by russell-taylor** [comment]
Thank you for taking the time to include this into MacPorts!  You should be aware that we are in the middle of making Reduce2 part of the CCTBX, where future development is planned.

**Comment by russell-taylor** [comment]
I talked with Jane Richardson about this.  The license terms are indeed as you describe.  Thanks again for getting this into MacPorts!
