### ISSUE TITLE
Encounter problem while installation

### ISSUE THREAD

**Issue by tao840813** [rlabduke/reduce#46]
Hi, my environment is ubuntu 20.04
i encounter a problem while "sudo make install" command.
Terminal shows these text and stops installing.
"gunzip -c -d ../reduce_wwPDB_het_dict.txt.gz > /usr/local/reduce_wwPDB_het_dict.txt
gzip: ../reduce_wwPDB_het_dict.txt.gz: No such file or directory"

Is there any solve?

**Comment by russell-taylor** [comment]
Sorry about that.  The file is no longer zipped so just needs to be copied.  I've modified the Makefile and pushed a new commit to master that should fix the problem.

**Comment by tao840813** [comment]
Thank you!
