### ISSUE TITLE
Provide a prefix at configure time

### ISSUE THREAD

**Issue by gcroci2** [rlabduke/reduce#49]
I installed `reduce` on a Linux machine where I don't have sudo privileges. The workaround I found was to manually modify the paths in `reduce/reduce_src/Makefile`, and add them to PATH in the `.bashrc` file. Then I run `make install` and the binary file was placed in my home directory, in the folder that I manually typed in the Makefile.  

The usual bypass for the sudo is by providing a prefix at configure time, or possibly also as a parameter to the make commands, but the `./configure` file is not present in the repo. It would be useful (and also a good practice) to include the option of having a prefix for the installation, instead of hard-coding the absolute path to the code.

**Comment by russell-taylor** [comment]
If you build using CMake, you can set the CMAKE_INSTALL_PREFIX and it will put the executable there under the bin/ directory and the HET dictionary in the prefix directory, telling the program where to find it.

**Comment by gcroci2** [comment]
> If you build using CMake, you can set the CMAKE_INSTALL_PREFIX and it will put the executable there under the bin/ directory and the HET dictionary in the prefix directory, telling the program where to find it.

Oh I see, thanks. It would be useful to add this to the readme.
