### ISSUE TITLE
Duplicate hydrogens added

### ISSUE THREAD

**Issue by nzrandol** [rlabduke/reduce#54]
Hello,

I'm trying to run Reduce on a bunch PDB files that contain a ligand in a pocket. Some of the ligands don't exist in the het_dict so I've been making fake CONECT databases to provide to Reduce. After running Reduce on some of these files, I've noticed that sometimes some hydrogens are duplicated / repeated in the output file. I think I set up the CONECT database right, but I'm not sure what is causing this issue.

I've attached one example where there is the ligand in a pocket (1b1h_pocket_ligand.txt) that I run Reduce on using the database (1b1h_reduce_conect.txt) to get the output (1b1h_pocket_ligand_reduce.txt). In that output, there are a number of duplicated hydrogens, specifically H22, H24, H35, H36, and H37. 
[1b1h_pocket_ligand.txt](https://github.com/rlabduke/reduce/files/13866877/1b1h_pocket_ligand.txt)
[1b1h_pocket_ligand_reduce.txt](https://github.com/rlabduke/reduce/files/13866876/1b1h_pocket_ligand_reduce.txt)
[1b1h_reduce_conect.txt](https://github.com/rlabduke/reduce/files/13866878/1b1h_reduce_conect.txt)

Any insight regarding this would be greatly appreciated!
Nick

**Comment by rwxayheee** [comment]
Hi @nzrandol , User here having done similar thing before. Took a quick look at the connect file and there seem to be some carbon atoms with same names: for example, there are two carbons named CE1 in your ligand (a polypeptide), which might be the cause of H22 being duplicated. Giving them unique names might get you through the duplicated hydrogens problem. 
Hope this is mildly helpul

**Comment by nzrandol** [comment]
Hey @rwxayheee, 

Thanks for your quick response! You're absolutely right, and these seems to have fixed my issue! Having atoms with the same name was definitely confusing Reduce.

Thanks again, Nick
