### ISSUE TITLE
Easy installation using package manager

### ISSUE THREAD

**Issue by eunos-1128** [rlabduke/reduce#55]
Dear all,

Thank you for developing the great package.

Currently, to install the latest version it seems that using make is the only option. 

However, are there any plans to make it possible to install via conda or OS package managers?

Best,

**Comment by eunos-1128** [comment]
@russell-taylor 

Thank you for explaining the situation.

Can I ask a question for `mmtbx.reduce2`?

Is there any documant describing `reduce` and `mmtbx.reduce2`?

I want to know the differences between the two versions because of switching.

**Comment by russell-taylor** [comment]
The relationship between Reduce and Reduce2 is described in the README.md associated with Reduce2 at https://github.com/cctbx/cctbx_project/blob/master/mmtbx/reduce/README.md and in the *Reduce2 Status and Planning* document linked from it, which is at https://docs.google.com/document/d/1ogzS6QlBnPJRGU2CNzHvw0KhV8E5fXdwO1TwUEM7GQc/edit#heading=h.pejxuuanr2uc

As of now, there are some serious outstanding issues with Reduce2 that might keep you from switching, even though there are improvements as well. These are listed in the documents pointed to.

**Comment by eunos-1128** [comment]
Thank you for your detailed answer.

I will check them out!
