### ISSUE TITLE
Floating point accuracy problem with flips can lead to invalid coordinates

### ISSUE THREAD

**Issue by sbstnk** [rlabduke/reduce#6]
When calculating the dihedral `rotangle` for a flip in `RotHingeDock_Flip` in `FlipMemo.cpp` (line 650) the `rotangle` can be `NaN` as a result of floating point accuracy issues. This then leads to all coordinates rotated by this angle to be invalid.

The underlying issue is found in the `dihedral` function in `toolclasses/Point3d.cpp`. In this function `dot(d, e)/(dmag*emag)` may not be exactly in the range from -1 to 1 due to floating point accuracy problems leading the following `acos` call to return `NaN`. Clamping the result of the division to this range would fix this problem. The same applies to `dot(f, e)/(fmag*emag)` later in that function.

This issue can be observed with PDB ID 3VI2, chain A, GLN 312.

**Comment by russell-taylor** [comment]
Pull request with the fix has been merged.
